name: Release

on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - run: npm ci
      - run: npm run lint
      - run: npm run build:lib
        env:
          NODE_ENV: production

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "version=$(node -e "console.log(require('./package-lock.json').packages['node_modules/@playwright/experimental-ct-react'].version)")" >> $GITHUB_OUTPUT
      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - run: npm test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.npm_token }}
        run: npx semantic-release

      - name: Get latest release version
        id: release-version
        run: echo "release=$(npm dist-tags)" >> $GITHUB_OUTPUT
      - name: Build docs
        run: npm run build:docs
        env:
          LATEST_RELEASE: ${{ steps.release-version.outputs.release }}
      - run: npm run build:demo
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_REACT_FIREBASE_LOGIN_273C0 }}
          channelId: live
          projectId: react-firebase-login-273c0
